# docker-compose.yml
services:
  web:
    env_file:
      - .env
    build: .
    ports:
      - "${WEB_EXPOSED_PORT}:${WEB_INTERNAL_PORT}"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    env_file:
      - .env
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXPOSED_PORT}:${DB_INTERNAL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./db/create_indexes.sql:/docker-entrypoint-initdb.d/02_create_indexes.sql
      - ./db/create_views.sql:/docker-entrypoint-initdb.d/03_create_views.sql
      - ./db/create_triggers.sql:/docker-entrypoint-initdb.d/04_create_triggers.sql
      - ./db/create_functions.sql:/docker-entrypoint-initdb.d/05_create_functions.sql
      - ./db/create_procedures.sql:/docker-entrypoint-initdb.d/06_create_procedures.sql
      - ./db/seed_roles_permissions.sql:/docker-entrypoint-initdb.d/07_seed_roles_permissions.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  postgres_data:
